#!/bin/sh

# https://github.com/taka-no-me/android-cmake
# https://github.com/chenxiaolong/android-cmake

rm -f CMakeCache.txt

cmake \
	-DCMAKE_TOOLCHAIN_FILE=android-cmake/android.toolchain.cmake \
	-DANDROID_NDK=~/android/android-ndk-r11c \
	-DCMAKE_BUILD_TYPE=Debug \
	-DANDROID_NATIVE_API_LEVEL=21 \
	-DANDROID_ABI="arm64-v8a" \
	-DANDROID_TOOLCHAIN_NAME=aarch64-linux-android-clang3.6 \
	$@
