#!/bin/sh

rm -f CMakeCache.txt

cmake \
	-DCMAKE_TOOLCHAIN_FILE=android-cmake/android.toolchain.cmake \
	-DANDROID_NDK=~/android/android-ndk-r10e \
	-DCMAKE_BUILD_TYPE=Debug \
	-DANDROID_NATIVE_API_LEVEL=21 \
	-DANDROID_ABI="arm64-v8a" \
	-DANDROID_TOOLCHAIN_NAME=aarch64-linux-android-clang3.5 \
	$@
