#!/bin/sh

if [ -z "$ANDROID_PRODUCT_OUT" ]; then
	echo "ANDROID_PRODUCT_OUT is not defined"
	exit -1
fi

FILES=""

# system/core
#FILES="$FILES system/lib64/libcutils.so"
#FILES="$FILES system/lib/libcutils.so"

# HIDL
#FILES="$FILES system/bin/hwservicemanager"
#FILES="$FILES system/lib64/libhidltransport.so"
#FILES="$FILES system/lib/libhidltransport.so"
#FILES="$FILES system/lib64/android.hidl.manager@1.0.so"
#FILES="$FILES system/lib/android.hidl.manager@1.0.so"

# frameworks/native
#FILES="$FILES system/lib64/libsurfaceflinger.so"
#FILES="$FILES system/lib/libsurfaceflinger.so"
#FILES="$FILES system/lib64/libgui.so"
#FILES="$FILES system/lib/libgui.so"
#FILES="$FILES system/lib64/libui.so"
#FILES="$FILES system/lib/libui.so"

# Common
#FILES="$FILES system/lib64/android.hardware.graphics.common@1.0.so"
#FILES="$FILES system/lib/android.hardware.graphics.common@1.0.so"

# IComposer
#FILES="$FILES system/lib64/android.hardware.graphics.composer@2.1.so"
#FILES="$FILES system/lib/android.hardware.graphics.composer@2.1.so"

# IMapper
#FILES="$FILES system/lib64/android.hardware.graphics.mapper@2.0.so"
#FILES="$FILES system/lib/android.hardware.graphics.mapper@2.0.so"

# IAllocator
#FILES="$FILES system/lib64/android.hardware.graphics.allocator@2.0.so"
#FILES="$FILES system/lib/android.hardware.graphics.allocator@2.0.so"

for f in $FILES; do
	adb push "$ANDROID_PRODUCT_OUT/$f" "$f"
done
