#!/bin/sh

generate_config() {
	cat <<EOF
duration_ms: 5000

buffers: {
    size_kb: 65536
    fill_policy: DISCARD
}

data_sources: {
    config {
        name: "linux.process_stats"
    }
}

data_sources {
  config {
    name: "track_event"
    track_event_config {
      #enabled_tags: "slow"
    }
  }
}

#data_sources {
#  config {
#    name: "gpu.counters.msm"
#    gpu_counter_config {
#      counter_period_ns: 100000
#    }
#  }
#}

data_sources: {
    config {
        name: "linux.ftrace"
        ftrace_config {
            atrace_categories: "am"
            atrace_categories: "audio"
            atrace_categories: "binder_driver"
            atrace_categories: "dalvik"
            atrace_categories: "freq"
            atrace_categories: "gfx"
            atrace_categories: "hal"
            atrace_categories: "idle"
            atrace_categories: "input"
            atrace_categories: "res"
            atrace_categories: "sched"
            atrace_categories: "sync"
            atrace_categories: "video"
            atrace_categories: "view"
            atrace_categories: "wm"
            atrace_categories: "workq"

            ftrace_events: "sched/sched_wakeup"

            ftrace_events: "drm/drm_vblank_event"
            ftrace_events: "drm/drm_vblank_event_delivered"
            ftrace_events: "gpu_scheduler/drm_sched_job"
            ftrace_events: "gpu_scheduler/drm_run_job"
            ftrace_events: "gpu_scheduler/drm_sched_process_job"
            ftrace_events: "dma_fence/dma_fence_init"
            ftrace_events: "dma_fence/dma_fence_emit"
            ftrace_events: "dma_fence/dma_fence_signaled"
            ftrace_events: "dma_fence/dma_fence_wait_start"
            ftrace_events: "dma_fence/dma_fence_wait_end"

            #atrace_categories: "irq"
            #ftrace_events: "raw_syscalls/sys_enter"
            #ftrace_events: "raw_syscalls/sys_exit"
            #ftrace_events: "syscalls/sys_enter_ioctl"
            #ftrace_events: "syscalls/sys_exit_ioctl"
        }
    }
}
EOF
}

TRACE_DIR="/data/misc/perfetto-traces"

if [ "$#" -eq 0 ]; then
	generate_config
	exit 0
fi

FN="$1"

# set ATRACE_TAG_APP for any cmdline
#adb shell setprop debug.atrace.app_number "1"
#adb shell setprop debug.atrace.app_0 "\*"

generate_config | adb shell perfetto -c - --txt -o "$TRACE_DIR/$FN"
adb pull "$TRACE_DIR/$FN"

adb shell setprop debug.atrace.app_number \"\"
