#!/bin/sh

PROJECTS="
	frameworks/native
	hardware/interfaces"

for i in $PROJECTS; do
	echo $i
	#(cd $i; git revert HEAD)
	#(cd $i; git reset --hard HEAD^)
done

#repo upload -t --br=blah $RPOJECTS
#repo prune $RPOJECTS
