#!/bin/bash

# before adb remount works..

OV="/data/vendor-overlay"

if ! adb shell mountpoint -q "$OV" 2>/dev/null; then
	echo "mounting $OV"
	adb shell mkdir -p "$OV"
	adb shell mount -t tmpfs none "$OV"
	adb shell mkdir "$OV/upper"
	adb shell mkdir "$OV/work"
fi

if ! adb shell mount | grep "on /vendor type overlay" > /dev/null; then
	echo "mounting /vendor"
	opts="lowerdir=/vendor,upperdir=$OV/upper,workdir=$OV/work"
	adb shell mount -t overlay -o "$opts" none /vendor
fi

adb shell setenforce 0

echo "done"
