#!/bin/sh

REPO_SYNC="repo sync -q"

now()
{
	date +%H:%M:%S
}

begin=`now`
(cd ../master-mirror && $REPO_SYNC -j64) || exit -1

middle=`now`
$REPO_SYNC -j128 -c

echo "BEGIN: $begin"
echo "MIDDLE: $middle"
echo "END: `now`"
