#!/bin/sh

TOP="$ANDROID_BUILD_TOP"
if [ -z "$TOP" ]; then
	TOP="$PWD"
fi

PROJECTS="
	bionic
	hardware/interfaces
	hardware/libhardware
	out/soong/.intermediates/hardware/interfaces/graphics/
	system/core
	system/libfmq
	system/libhidl
	system/libhwbinder
	system/libvintf
	frameworks/av
	frameworks/base/libs
	frameworks/base/core/jni
	frameworks/native"

(cd "$TOP" && ctags -R $PROJECTS)
