#!/bin/sh

set_governor=""
if [ "$#" -gt 0 ]; then
	set_governor="$1"
fi

for i in /sys/devices/system/cpu/cpufreq/policy*/scaling_governor; do
	if [ -n "$set_governor" ]; then
		echo "$set_governor" > "$i"
	fi

	echo -n "$i: "
	cat "$i"
done
