#!/bin/sh

if [ "$#" -ge 1 ]; then
	dst_base="$1"
else
	dst_base="$HOME"
fi

dst_base=$(realpath "$dst_base")
src_base=$(dirname "$(realpath "$0")")

create_xdg_base_dirs() {
	xdg_dirs="
		.cache
		.config
		.local/share
		.local/state
	"

	for dir in $xdg_dirs; do
		mkdir -p -m 0700 "$dst_base/$dir"
	done
}

install() {
	src="$src_base/$1"
	dst="$dst_base/$2"
	name="$2"

	if [ -e "$dst" ]; then
		[ "$(realpath "$dst")" = "$src" ] || echo "$dst already exists"
		return
	fi

	dst_dir=$(dirname "$dst")
	if ! mkdir -p -m 0700 "$dst_dir"; then
		return
	fi

	src_rel=$(realpath --relative-to="$dst_dir" "$src")
	if ln -sfn "$src_rel" "$dst"; then
		echo "$name installed"
	fi
}

create_xdg_base_dirs

install "alacritty.toml" ".config/alacritty/alacritty.toml"
install "fontconfig-fonts.conf" ".config/fontconfig/fonts.conf"
install "gdbearlyinit" ".config/gdb/gdbearlyinit"
install "gdbinit" ".config/gdb/gdbinit"
install "gitconfig" ".config/git/config"
(umask 077 && touch "$dst_base/.config/git/credentials")
install "gpg-agent.conf" ".gnupg/gpg-agent.conf"
install "i3status-config" ".config/i3status/config"
install "msmtp-aliases" ".config/msmtp/aliases"
install "msmtprc" ".config/msmtp/config"
install "pinentry-preexec" ".config/pinentry/preexec"
install "sh-rc.sh" ".bashrc"
install "sh-profile.sh" ".bash_profile"
install "ssh-config" ".ssh/config"
install "sway-config" ".config/sway/config"
install "systemd-fetch-repos.service" ".config/systemd/user/fetch-repos.service"
install "systemd-fetch-repos.timer" ".config/systemd/user/fetch-repos.timer"
install "systemd-sway.service" ".config/systemd/user/sway.service"
install "systemd-sway-session.target" ".config/systemd/user/sway-session.target"
install "tmux.conf" ".config/tmux/tmux.conf"
install "vimrc" ".vim/vimrc"
install "vim-pack" ".vim/pack"
