#!/bin/sh

ETC=$HOME/olv-etc
DST=$HOME

install() {
	if [ -h "$2" -a "$1" = "`readlink $2`" ]; then
		return
	elif [ -f "$2" ]; then
		echo "$2 already exists"
		return
	fi

	if mkdir -p "`dirname $2`" && ln -s "$1" "$2"; then
		echo "`basename $1` installed"
	fi
}

install "$ETC/bashrc" "$DST/.bashrc"
install "$ETC/bash_paths" "$DST/.bash_paths"
install "$ETC/bash_aliases" "$DST/.bash_aliases"
install "$ETC/bash_profile" "$DST/.bash_profile"

install "$ETC/gitconfig" "$DST/.config/git/config"
install "$ETC/ssh-config" "$DST/.ssh/config"
install "$ETC/vimrc" "$DST/.vim/vimrc"
install "$ETC/tmux.conf" "$DST/.tmux.conf"

install "$ETC/sway-session" "$DST/.local/bin/sway-session"
install "$ETC/sway-session-autostart" "$DST/.local/bin/sway-session-autostart"
install "$ETC/sway-config" "$DST/.config/sway/config"
install "$ETC/i3status-config" "$DST/.config/i3status/config"
install "$ETC/alacritty.yml" "$DST/.config/alacritty/alacritty.yml"
