#!/bin/sh

if [ ! -f meson.build ]; then
        echo "not a Mesa directory"
        exit
fi

OUT="out"
rm -rf $OUT

BOARD=""
HOST=""
DRIVERS=""
DRI=""
SYSROOT="/build/$BOARD"
DUT=""

generate_cross_file() {
	BOARD_COMPILER_FLAGS=""
	# from make.defaults
	CXXEXCEPTIONS_FLAGS="'-fno-exceptions', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables'"

	# from make.conf.common
	CROS_LDFLAGS="'--sysroot=$SYSROOT', '-Wl,-O2', '-Wl,--as-needed'"
	CROS_CFLAGS="'--sysroot=$SYSROOT', $BOARD_COMPILER_FLAGS, $CXXEXCEPTIONS_FLAGS"

	cat <<EOF
[binaries]
ar = '/usr/bin/$HOST-ar'
c = '/usr/bin/$HOST-clang'
cpp = '/usr/bin/$HOST-clang++'
strip = '/usr/bin/$HOST-strip'
pkgconfig = '$SYSROOT/build/bin/pkg-config'

[properties]
c_args = [$CROS_CFLAGS]
c_link_args = [$CROS_LDFLAGS]
cpp_args = [$CROS_CFLAGS]
cpp_link_args = [$CROS_LDFLAGS]

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7a'
endian = 'little'
EOF
}

generate_install_script() {
	SRC="lib"
	DST="$SYSROOT/usr/lib"
	DEBUG_DST="$SYSROOT/usr/lib/debug/usr/lib"

	cat <<EOF
set -e

ninja

sudo $HOST-objcopy --only-keep-debug $SRC/dri/$DRI $DEBUG_DST/dri/$DRI.debug
sudo $HOST-objcopy --strip-debug --add-gnu-debuglink=$DEBUG_DST/dri/$DRI.debug $SRC/dri/$DRI $DST/dri/$DRI
scp $DST/dri/$DRI $DUT:/usr/lib/dri
EOF
}

mkdir $OUT
generate_cross_file > $OUT/cross_file.txt

generate_install_script > $OUT/cros-mesa-install
chmod +x $OUT/cros-mesa-install

mkdir -p $OUT/lib/dri
ln -sf ../../src/gallium/targets/dri/libgallium_dri.so $OUT/lib/dri/$DRI

meson $OUT --cross-file $OUT/cross_file.txt \
        -D glx=disabled \
        -D gbm=false \
        -D dri-drivers= \
        -D gallium-xa=false \
        -D llvm=false \
        -D dri3=false \
        -D buildtype=debug \
        -D warning_level=1 \
        -D shared-glapi=true \
        -D opengl=true \
        -D gles1=false \
        -D gles2=true \
        -D egl=true \
        -D platforms=surfaceless \
        -D gallium-drivers=$DRIVERS \
        -D vulkan-drivers= \
        $@
