#!/bin/sh

# NOT for chromeos, but for chromebooks converted to linux
# dd if=/dev/zero of=Image.bl bs=512 count=1

set -xe

DUT="coachz"

lz4 -zf arch/arm64/boot/Image Image.lz4
dtc -I dts -O dtb -p 1024 -o Image.fit Image.its
futility vbutil_kernel --pack Image.vboot --vmlinuz Image.fit --config Image.cmdline --bootloader Image.bl --version 1 --arch aarch64 --keyblock /usr/share/vboot/devkeys/kernel.keyblock --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk

#tar zc -C MODULES lib/modules | ssh $DUT sudo tar zx --no-same-owner -C /

scp Image.vboot $DUT:~
ssh $DUT sudo cp Image.vboot /dev/mmcblk1p2
ssh $DUT sudo cgpt add -i 2 -S 0 -T 1 -P15 /dev/mmcblk1
ssh $DUT sudo reboot

# /dts-v1/;
# 
# / {
# 	images {
# 		kernel@1{
# 			description = "kernel";
# 			data = /incbin/("Image.lz4");
# 			type = "kernel_noload";
# 			arch = "arm64";
# 			os = "linux";
# 			compression = "lz4";
# 			load = <0>;
# 			entry = <0>;
# 		};
# 		fdt@1{
# 			data = /incbin/("Image.dtb");
# 			type = "flat_dt";
# 			arch = "arm64";
# 			compression = "none";
# 			hash@1{
# 				algo = "sha1";
# 			};
# 		};
# 	};
# 	configurations {
# 		conf@1{
# 			kernel = "kernel@1";
# 			fdt = "fdt@1";
# 		};
# 	};
# };
