#!/bin/sh

cros_setup_env_common() {
	# src/third_party/chromiumos-overlay/profiles/targets/chromeos/make.defaults
	CXXEXCEPTIONS_FLAGS="-fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables"

	# src/third_party/chromiumos-overlay/chromeos/config/make.conf.generic-target
	COMMON_COMPILER_FLAGS="-O2 -pipe ${MARCH_TUNE} ${BOARD_COMPILER_FLAGS} -g ${CXXEXCEPTIONS_FLAGS}"

	# src/third_party/chromiumos-overlay/chromeos/config/make.conf.common
	LDFLAGS="-Wl,-O2 -Wl,--as-needed" \

	CROSS_COMPILE="/usr/bin/$HOST-"
	DEBUG_FILE_DIRECTORY="$SYSROOT/usr/lib/debug"
	PKG_CONFIG="$SYSROOT/build/bin/pkg-config"
}

cros_setup_env_cheza() {
	SYSROOT="/build/cheza"

	# src/overlays/chipset-qc845/toolchain.conf
	# src/third_party/chromiumos-overlay/profiles/features/llvm/arm/make.defaults
	HOST="armv7a-cros-linux-gnueabihf"

	# src/overlays/chipset-qc845/profiles/base/make.defaults
	BOARD_COMPILER_FLAGS="-march=armv8-a+crc -mtune=cortex-a57.cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard"

	cros_setup_env_common
}

cros_setup_env_cheza

./configure $@ \
	--host=$HOST \
	CC="${CROSS_COMPILE}clang" \
	CXX="${CROSS_COMPILE}clang++" \
	CFLAGS="--sysroot=$SYSROOT $COMMON_COMPILER_FLAGS" \
	CXXFLAGS="--sysroot=$SYSROOT $COMMON_COMPILER_FLAGS" \
	LDFLAGS="$LDFLAGS" \
	PKG_CONFIG="$PKG_CONFIG"
