#!/bin/sh

CROS="$HOME/cros"
if [ -z "$CROS" ]; then
	CROS="$PWD"
fi

PROJECTS="src/platform/drm-tests
	  src/platform/minigbm
	  src/third_party/kernel/v4.19/include/uapi
	  src/third_party/libdrm
	  src/third_party/mesa
	  src/third_party/virglrenderer"
(cd "$CROS" && ctags -R $PROJECTS)

LOCAL_PROJECTS="src/third_party/kernel/v4.19"
for project in $LOCAL_PROJECTS; do
	(cd "$CROS/$project" && ctags -R)
done
