#!/bin/sh

BOARD=""
HOST=""
DRIVERS=""
MARCH=""

SYSROOT="/build/$BOARD"

if [ ! -x ./configure ]; then
	autoreconf -f -v -i -I $SYSROOT/usr/share/aclocal
fi

export PATH="/usr/local/bin:/usr/bin:/bin:$SYSROOT/build/bin"
export PKG_CONFIG="$SYSROOT/build/bin/pkg-config"
export CC="$HOST-clang"
export CXX="$HOST-clang++"
export CPPFLAGS="--sysroot=$SYSROOT"
export CFLAGS="-O2 -pipe -g $MARCH -UENABLE_SHADER_CACHE"
export CXXFLAGS="$CFLAGS -std=gnu++11"
export LDFLAGS="--sysroot=$SYSROOT -Wl,-O2 -Wl,--as-needed"

APIS="--disable-dri3
      --disable-glx
      --disable-gbm
      --disable-gles1
      --enable-gles2
      --enable-shared-glapi"

FEATURES=""

DRIVERS="--with-dri-drivers=
         --with-vulkan-drivers=
	 --with-gallium-drivers=$DRIVERS"

PLATFORMS="--with-platforms=surfaceless"

FLAGS="--prefix=/usr --enable-debug"

./configure --host=$HOST $APIS $FEATURES $PLATFORMS $DRIVERS $FLAGS $@
