#!/bin/sh

PORT=1234

PROJECTS="src/platform/drm-tests
	  src/platform/minigbm
	  src/third_party/libdrm
	  src/third_party/mesa"
DIRECTORIES="."
for project in $PROJECTS; do
	DIRECTORIES="$DIRECTORIES:$HOME/trunk/$project"
done

$HOST-gdb \
        -ex "set sysroot /build/$BOARD" \
        -ex "set solib-absolute-prefix /build/$BOARD" \
        -ex "set debug-file-directory /build/$BOARD/usr/lib/debug" \
        -ex "set directories $DIRECTORIES" \
        -ex "target remote :$PORT" \
	$@
