#!/bin/sh

APIS="--enable-opengl
      --enable-gles1
      --enable-gles2
      --enable-openvg
      --enable-egl
      --enable-dri
      --enable-glx"

#APIS="$APIS --enable-opencl"

FEATURES="--enable-gallium-egl
          --enable-gallium-tests
          --with-egl-platforms=x11,null
          --enable-shared-glapi
          --enable-glx-tls
          --enable-texture-float"

DRIVERS="--with-dri-drivers=i965,swrast
         --with-gallium-drivers=swrast,i965"

FLAGS="--enable-debug"

MISC="--with-clang-libdir=/usr/include
      --with-opencl-libdir=\${libdir}/opencl:$HOME/fdo/mesa/mesa/src/gallium/targets/pipe-loader"

./configure $APIS $DRIVERS $FEATURES $FLAGS $MISC $@ \
	CC="ccache gcc" CXX="ccache g++" \
	CFLAGS="-O0" CXXFLAGS="-O0"
