#!/bin/sh

APIS="--enable-opengl
      --enable-gles1
      --enable-gles2
      --enable-openvg
      --disable-opencl
      --enable-egl
      --enable-dri
      --enable-glx
      --disable-glu"

FEATURES="--enable-gallium-egl
          --with-egl-platforms=x11,null
          --enable-shared-glapi
          --enable-glx-tls
          --enable-texture-float"

DRIVERS="--with-dri-drivers=i965,swrast
         --with-gallium-drivers=swrast,i965"

FLAGS="--enable-debug"

./configure $APIS $DRIVERS $FEATURES $FLAGS $@ \
	CC="ccache gcc" CXX="ccache g++" \
	CFLAGS="-O0" CXXFLAGS="-O0"
