#!/bin/sh

APIS="--enable-opengl
      --enable-gles1
      --enable-gles2
      --enable-egl
      --enable-dri
      --enable-glx
      --disable-xvmc"

#APIS="$APIS --enable-opencl"

FEATURES="--with-egl-platforms=x11,null
          --enable-shared-glapi
          --enable-glx-tls
          --enable-texture-float"

FEATURES="$FEATURES --disable-gallium-llvm"
#FEATURES="$FEATURES --enable-gallium-tests"

DRIVERS="--with-dri-drivers=i965,swrast
         --with-gallium-drivers=swrast,ilo"

FLAGS="--enable-debug"

MISC="--with-clang-libdir=/usr/include
      --with-opencl-libdir=\${libdir}/opencl:$HOME/fdo/mesa/mesa/src/gallium/targets/pipe-loader"

./configure $APIS $DRIVERS $FEATURES $FLAGS $MISC $@ \
	CC="ccache gcc" CXX="ccache g++" CFLAGS="-g3 -O0" CXXFLAGS="-g3 -O0"
