#!/bin/sh

rm -f ./CMakeCache.txt

cmake \
	-DCMAKE_C_COMPILER="/usr/bin/ccache" \
	-DCMAKE_C_COMPILER_ARG1="/usr/bin/gcc" \
	-DCMAKE_CXX_COMPILER="/usr/bin/ccache" \
	-DCMAKE_CXX_COMPILER_ARG1="/usr/bin/g++" \
	-DCMAKE_BUILD_TYPE=Debug \
	-DCMAKE_C_FLAGS="-ggdb3 -O0" \
	-DCMAKE_CXX_FLAGS="-ggdb3 -O0" \
	$@
