#!/bin/sh

GENERAL_OPTS="
	-name my-vm,debug-threads=on
	-mon my-serial"

MACHINE_OPTS="
	-machine q35,pflash0=my-efi,pflash1=my-efivars
	-cpu Broadwell
	-accel kvm
	-smp 2
	-m 2G
	-nodefaults"

EFI_OPTS="
	-blockdev driver=file,node-name=my-efi,read-only=on,filename=pc-bios/edk2-x86_64-code.fd
	-blockdev driver=file,node-name=my-efivars,filename=arch-efivars.fd"

DISPLAY_OPTS="
	-device virtio-vga
	-display sdl,gl=on"

INPUT_OPTS="
	-device virtio-keyboard
	-device virtio-mouse"

SERIAL_OPTS="
	-device virtio-serial
	-device virtserialport,chardev=my-serial
	-chardev stdio,id=my-serial,mux=on"

# also ttyS0
SERIAL_OPTS="$SERIAL_OPTS -device pci-serial,chardev=my-serial"

NETWORK_OPTS="
	-device virtio-net,netdev=my-net
	-netdev user,id=my-net,hostfwd=tcp::2222-:22"

BLOCK_OPTS="
	-device ide-hd,drive=my-drive
	-blockdev driver=file,node-name=my-image,filename=arch.qcow2
	-blockdev driver=qcow2,node-name=my-drive,file=my-image"

export SDL_VIDEO_ALLOW_SCREENSAVER=1

./x86_64-softmmu/qemu-system-x86_64 \
	$GENERAL_OPTS \
	$MACHINE_OPTS \
	$EFI_OPTS \
	$DISPLAY_OPTS \
	$INPUT_OPTS \
	$SERIAL_OPTS \
	$NETWORK_OPTS \
	$BLOCK_OPTS \
	"$@"
