#!/bin/sh

# I like 10pt which is 22.2px on 160dpi.  gnome and most softwares/libraries
# default to 11pt and assume 96dpi, which is 14.6px.  Scale it.
gsettings set org.gnome.desktop.interface text-scaling-factor 1.5
#gsettings set org.gnome.desktop.interface cursor-size 36

nm-applet --indicator &
fcitx5 &

swayidle -w \
    timeout 300 'swaylock -f -c 000000' \
    timeout 330 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
    before-sleep 'swaylock -f -c 000000' \
    after-resume 'swaymsg "output * enable"' &
