#!/bin/sh

# SSH_AUTH_SOCK has been explicitly set in sway-session
ssh-agent -a "$SSH_AUTH_SOCK"

nm-applet --indicator &
fcitx5 &

swayidle -w \
    timeout 300 'swaylock -f -c 000000' \
    timeout 330 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
    before-sleep 'swaylock -f -c 000000' \
    after-resume 'swaymsg "output * enable"' &
