#!/bin/sh

set_envs() {
	export NO_AT_BRIDGE=1

	export GTK_IM_MODULE=fcitx
	export QT_IM_MODULE=fcitx
	export XMODIFIERS=@im=fcitx

	export GDK_BACKEND=wayland
	export QT_QPA_PLATFORM=wayland
	export SDL_VIDEODRIVER=wayland
}

# set envs, mainly for apps started by sway
set_envs

exec sway > "$HOME/.sway-errors" 2>&1
