name: kavita

services:
  kavita:
    image: docker.io/jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - ${COMPOSE_PROJECT_DIR}/kavita-config:/kavita/config
      - /srv/manga:/manga:ro
    ports:
      - "5000:5000"
    restart: unless-stopped
