services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /home/pod-jellyfin/jellyfin-config:/config
      - /home/pod-jellyfin/jellyfin-cache:/cache
      - /srv/media:/media:ro
    ports:
      - "8096:8096"
    restart: unless-stopped
