name: prom

services:
  node-exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /:/host/rootfs:ro
      - /proc:/host/procfs:ro
      - /sys:/host/sysfs:ro
    command:
      - '--path.rootfs=/host/rootfs'
      - '--path.procfs=/host/procfs'
      - '--path.sysfs=/host/sysfs'
      - '--collector.filesystem.mount-points-exclude=^/(dev|mnt|proc|run|sys|tmp)($$|/)'
    restart: unless-stopped
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ${COMPOSE_PROJECT_DIR}/prometheus-config:/etc/prometheus
      - ${COMPOSE_PROJECT_DIR}/prometheus-data:/prometheus
    restart: unless-stopped
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    volumes:
      - ${COMPOSE_PROJECT_DIR}/grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
