name: ha

services:
  ha:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: ha
    volumes:
      - ${COMPOSE_PROJECT_DIR}/ha-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    network_mode: host
    restart: unless-stopped
