name: jellyfin

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - ${COMPOSE_PROJECT_DIR}/jellyfin-config:/config
      - ${COMPOSE_PROJECT_DIR}/jellyfin-cache:/cache
      - /srv/media:/media:ro
    ports:
      - "8096:8096"
    healthcheck:
      disable: true
    restart: unless-stopped
