services:
  kavita:
    image: docker.io/jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - /srv/manga:/manga
      - /home/kavita/kavita-config/:/kavita/config
    ports:
      - "5000:5000"
    restart: unless-stopped
