name: omada

services:
  omada:
    image: docker.io/mbentley/omada-controller:latest
    container_name: omada
    environment:
      - TZ=America/Los_Angeles
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - ./omada-data:/opt/tplink/EAPController/data
      - ./omada-logs:/opt/tplink/EAPController/logs
    ports:
      - "8043:8043"
      - "8088:8088"
      - "8843:8843"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811-29816:29811-29816"
    healthcheck:
      disable: true
    stop_grace_period: 60s
    restart: unless-stopped
