menu title NanoPi R5C
timeout 10

label debian
	kernel /debian.kernel
	initrd /debian.initrd
	fdt /debian.dtb
	append console=ttyS2,1500000 console=tty0 root=PARTUUID=ee4394f7-9286-224a-8406-6c51ab211459 fsck.repair=yes

label debian-prev
	kernel /debian.kernel.old
	initrd /debian.initrd.old
	fdt /debian.dtb.old
	append console=ttyS2,1500000 console=tty0 root=PARTUUID=ee4394f7-9286-224a-8406-6c51ab211459 fsck.repair=yes
