#!/bin/bash

# This script is transient while adb remount is persistent.

OV_TMPFS="/data/overlay-remount"
OV_REMOUNTS="
	/system/bin
	/system/lib64
	/vendor/bin
	/vendor/etc
	/vendor/lib64
"

if ! adb shell whoami | grep -q root; then
	echo 'please adb root first'
	exit 1
fi

if ! adb shell mountpoint -q "$OV_TMPFS" 2>/dev/null; then
	echo "mounting $OV_TMPFS"
	adb shell mkdir -p "$OV_TMPFS"
	adb shell mount -t tmpfs none "$OV_TMPFS"
fi

for remount in $OV_REMOUNTS; do
	if ! adb shell mount | grep -q "none on $remount type overlay"; then
		echo "preparing $OV_TMPFS for $remount"
		adb shell mkdir -p "$OV_TMPFS/$remount-upper"
		adb shell mkdir -p "$OV_TMPFS/$remount-work"

		echo "mounting $remount"
		opts="lowerdir=$remount,upperdir=$OV_TMPFS/$remount-upper,workdir=$OV_TMPFS/$remount-work"
		adb shell mount -t overlay -o "$opts" none $remount
	fi
done

echo "disabling selinux"
adb shell setenforce 0

echo "done"
