#!/bin/sh

TOP="$ANDROID_BUILD_TOP"
if [ -z "$TOP" ]; then
	TOP="$PWD"
fi

PROJECTS="
	bionic
	external/googletest
	frameworks/av
	frameworks/base/cmds
	frameworks/base/core/jni
	frameworks/base/libs
	frameworks/native
	hardware/interfaces
	hardware/libhardware
	out/soong/.intermediates/hardware/interfaces/graphics/
	system/core
	system/hwservicemanager
	system/libfmq
	system/libhidl
	system/libhwbinder
	system/libvintf
	system/tools/hidl/utils"

(cd "$TOP" && ctags -R $PROJECTS)
(cd "$TOP/frameworks/base" && ctags -R)
