#!/bin/sh

adb shell settings put global package_verifier_enable 0
adb shell settings put global stay_on_while_plugged_in 3
adb shell cmd user activities-allowlist android.os.usertype.system.HEADLESS disable
