#!/bin/sh

TOP="$ANDROID_BUILD_TOP"
if [ -z "$TOP" ]; then
	TOP="$PWD"
fi

REPOS="
	bionic
	external/avb
	external/drm_hwcomposer
	external/minigbm
	frameworks/av
	frameworks/native
	hardware/interfaces
	hardware/libhardware
	packages/modules/adb
	system/core
	system/libbase
	system/logging
"

EXTRAS="
	frameworks/base/cmds
	frameworks/base/core/jni
	frameworks/base/libs
	out/soong/.intermediates/hardware/interfaces/graphics
"

(cd "$TOP" && ctags -R $REPOS $EXTRAS)
(cd "$TOP/frameworks/base" && ctags -R)
