#!/bin/sh

set -e

mirror="https://mirror.fcix.net/archlinux"
username="olv"

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <NEWROOT>"
	exit 1
fi
newroot="$1"

if [ $(id -u) -ne 0 ]; then
	echo "Please run as root."
	exit 1
fi

chroot_bootstrap1() {
	if [ -d "$newroot" ]; then
		return
	fi

	read -p "$newroot does not exist.  Bootstrap? " unused
	mkdir -p "$newroot"
	touch "$newroot/arch-chroot-bootstrap2"
}

unshare_and_restart() {
	echo "entering namespace..."

	user_ns_args="--user --map-users=auto --map-groups=auto"
	# no --user
	user_ns_args=""
	pid_ns_args="--pid --fork"
	# no --net
	misc_ns_args="--mount --ipc --uts --cgroup --time"

	exec unshare $user_ns_args $pid_ns_args $misc_ns_args "$0" "$@"
}

chroot_bootstrap2() {
	if [ ! -f "$newroot/arch-chroot-bootstrap2" ]; then
		return
	fi

	echo "downloading rootfs..."

	curl "$mirror/iso/latest/archlinux-bootstrap-x86_64.tar.gz" | \
		tar -zx --warning=no-unknown-keyword -C "$newroot" --strip 1

	touch "$newroot/arch-chroot-bootstrap3"
	rm -f "$newroot/arch-chroot-bootstrap2"
}

chroot_mount_pseudo() {
	echo "mounting pseudo filesystems..."

	# pacman CheckSpace expects / to be a mountpoint
	mount --bind "$newroot" "$newroot"

	mount --rbind "/dev" "$newroot/dev"
	mount --bind -o ro "/sys" "$newroot/sys"
	mount -t proc -o ro none "$newroot/proc"

	mount -t tmpfs none "$newroot/run"
	mount -t tmpfs none "$newroot/tmp"
}

chroot_fix_network() {
	echo "fixing network..."

	cp /etc/resolv.conf "$newroot/etc/resolv.conf"
}

chroot_bootstrap3() {
	if [ ! -f "$newroot/arch-chroot-bootstrap3" ]; then
		return
	fi

	echo "bootstrapping..."

	ln -sf /usr/share/zoneinfo/America/Los_Angeles "$newroot/etc/localtime"

	locale="en_US.UTF-8"
	echo "LANG=$locale" > "$newroot/etc/locale.conf"
	sed -i "s/^#$locale/$locale/" "$newroot/etc/locale.gen"
	chroot "$newroot" locale-gen

	echo "Server = $mirror/\$repo/os/\$arch" > "$newroot/etc/pacman.d/mirrorlist"
	chroot "$newroot" pacman-key --init
	chroot "$newroot" pacman-key --populate
	chroot "$newroot" pacman -R --noconfirm arch-install-scripts || true
	chroot "$newroot" pacman -Syu --noconfirm inetutils sudo vim git

	policy="%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
	sed -i "s/^# $policy/$policy/" "$newroot/etc/sudoers"

	chroot "$newroot" useradd -m -G wheel "$username"
	echo "root:test0000" | chroot "$newroot" chpasswd
	echo "$username:test0000" | chroot "$newroot" chpasswd

	if [ "$username" = "olv" ]; then
		rm -f "$newroot/home/$username/.bash"*
		chroot "$newroot" su - "$username" -c "git clone https://github.com/olvaffe/olv-etc.git" || true
		chroot "$newroot" su - "$username" -c "./olv-etc/create-links"
	fi

	rm -f "$newroot/pkglist.x86_64.txt"
	rm -f "$newroot/version"
	rm -f "$newroot/arch-chroot-bootstrap3"

	echo
	echo "bootstrapped $newroot!"
}

chroot_fix_hostname() {
	echo "fixing hostname..."

	chroot "$newroot" hostname "arch-chroot"
}

chroot_mount_sockets() {
	echo "bind-mounting sockets..."

	wl_sock=$(find /run -name "wayland-*" -type s -print -quit 2>/dev/null || true)
	if [ -n "$wl_sock" ]; then
		wl_bind="/run/$(basename "$wl_sock")"

		touch "$newroot/$wl_bind"
		mount --bind -o ro "$wl_sock" "$newroot/$wl_bind"
		export WAYLAND_DISPLAY="$wl_bind"
	fi

	x11_sock=$(find /tmp/.X11-unix -name "X*" -type s -print -quit 2>/dev/null || true)
	if [ -n "$x11_sock" ]; then
		mkdir -p "$newroot/$(dirname "$x11_sock")"
		touch "$newroot/$x11_sock"
		export DISPLAY=$(echo $(basename "$x11_sock") | tr X :)
		mount --bind -o ro "$x11_sock" "$newroot/$x11_sock"
	fi

	perfetto_sock="/tmp/perfetto-producer"
	if [ -S "$perfetto_sock" ]; then
		touch "$newroot/$perfetto_sock"
		mount --bind -o ro "$perfetto_sock" "$newroot/$perfetto_sock"
	fi

	perfetto_dir="/run/perfetto"
	if [ -d "$perfetto_dir" ]; then
		mkdir "$newroot/$perfetto_dir"
		mount --bind -o ro "$perfetto_dir" "$newroot/$perfetto_dir"
	fi
}

chroot_enter() {
	echo "entering $newroot..."
	echo

	chroot "$newroot" su -w WAYLAND_DISPLAY,DISPLAY - "$username"
}

chroot_bootstrap1
if [ "$$" -ne "1" ]; then
	unshare_and_restart "$@"
fi
chroot_bootstrap2
chroot_mount_pseudo
chroot_fix_network
chroot_bootstrap3
chroot_fix_hostname
chroot_mount_sockets
chroot_enter
