#!/bin/sh

# Assuming 4 types of devices
#
#  - workstations
#  - duts
#  - containers
#  - servers

# for bootstrapping (~800M)
cli_min="
	base
	btrfs-progs
	dosfstools
	sudo
	vim
"

# for all devices (~50M)
cli_base="
	$cli_min
	htop
	ldns
	logrotate
	lsof
	openssh
	rsync
	usbutils
"

# for all except servers (~300M)
cli_std="
	$cli_base
	bc
	ctags
	git
	man-db
	man-pages
	perf
	python
	strace
	tmux
	trace-cmd
	unzip
	vulkan-tools
	zip
"

# for workstations (~550M)
cli_full="
	$cli_std
	android-tools
	jq
	mesa-utils
	msmtp
	nordvpn-bin
	picocom
	wireguard-tools
"

# for gui testing (~200M)
gui_min="
	alacritty
	brightnessctl
	i3status
	noto-fonts
	polkit
	sway
	swayidle
	wayland-utils
"

# for simple use (~150M)
gui_base="
	$gui_min
	grim
	mako
	slurp
	swayimg
	swaylock
	wl-clipboard
"

# for real use (~1250M)
gui_std="
	$gui_base
	fcitx5-chewing
	fcitx5-configtool
	fcitx5-gtk
	google-chrome
	gtk4
	noto-fonts-cjk
	noto-fonts-emoji
	pipewire-pulse
"

# for optional features (~300M)
gui_full="
	$gui_std
	cups
	mpv
	xdg-desktop-portal-gtk
	xdg-desktop-portal-wlr
"

# for compile (~350M)
dev_min="
	base-devel
	ccache
	cmake
	meson
"

# for development (~450M)
dev_base="
	$dev_min
	clang
	gdb
"

# for mesa (~250M)
dev_mesa="
	glslang
	libclc
	llvm
	spirv-llvm-translator
"

# dtc and vboot-minimal-git are for cros kernel
dev_kernel="
	dtc
	vboot-minimal-git
"

# for cross-compile (~600M)
dev_cross="
	aarch64-linux-gnu-gcc
	qemu-user-static-binfmt
"

kernel_common="
	zram-generator
"

kernel_x86="
	$kernel_common
	linux
"

kernel_custom="
	$kernel_common
"

hw_x86="
	  turbostat
"

hw_arm="
	archlinuxarm-keyring
"

hw_uefi="
	sbctl
	systemd-ukify
"

hw_intel="
	linux-firmware-intel
	intel-ucode
	vulkan-intel
"

hw_amd="
	amd-ucode
	linux-firmware-amdgpu
	vulkan-radeon
"

hw_qcom="
	linux-firmware-qcom
	vulkan-freedreno
"

hw_wifi="
	iw
	iwd
	wireless-regdb
"

hw_usbnet="
	linux-firmware-realtek
"

hw_dut="
	seatd
"

hw_xps="
	bcm20702a1-firmware
	broadcom-wl-dkms
	linux-headers
	wpa_supplicant
"

cros_x86="
	cgpt-bin
"

cros_arm="
	vboot-utils
"

cros_crostini="
	cros-container-guest-tools-git
"

pkgs=""

host="$(uname -n)"
case "$host" in
	"t580"|"xps")
		pkgs="$pkgs $cli_full $gui_full"
		pkgs="$pkgs $dev_base $dev_mesa $dev_kernel $dev_cross"
		pkgs="$pkgs $kernel_x86"
		pkgs="$pkgs $hw_x86 $hw_uefi $hw_intel $hw_wifi"

		if [ "$host" = "xps" ]; then
			pkgs="$pkgs $hw_xps"
		fi
		;;
	"brya"|"skyrim")
		pkgs="$pkgs $cli_std $gui_min"
		pkgs="$pkgs $dev_base $dev_mesa"
		pkgs="$pkgs $kernel_custom"
		pkgs="$pkgs $hw_x86 $hw_usbnet $hw_dut"
		pkgs="$pkgs $cros_x86"

		if [ "$host" = "brya" ]; then
			pkgs="$pkgs $hw_intel"
		elif [ "$host" = "skyrim" ]; then
			pkgs="$pkgs $hw_amd"
		fi
		;;
	"navi"|"corsola"|"cherry"|"trogdor")
		pkgs="$pkgs $cli_std $gui_min"
		pkgs="$pkgs $dev_base $dev_mesa"
		pkgs="$pkgs $kernel_custom"
		pkgs="$pkgs $hw_arm $hw_usbnet $hw_dut"
		pkgs="$pkgs $cros_arm"

		if [ "$host" = "trogdor" ]; then
			pkgs="$pkgs $hw_qcom"
		fi
		;;
	"s15"|"hamoa"|"purwa"|"opi")
		pkgs="$pkgs $cli_std $gui_min"
		pkgs="$pkgs $dev_base $dev_mesa"
		pkgs="$pkgs $kernel_custom"
		pkgs="$pkgs $hw_arm $hw_usbnet $hw_dut"

		if [ "$host" = "s15" ]; then
			pkgs="$pkgs $hw_uefi $hw_qcom $hw_wifi"
		elif [ "$host" = "hamoa" -o "$host" = "purwa" ]; then
			pkgs="$pkgs $hw_uefi $hw_qcom"
		fi
		;;
	"crostini")
		pkgs="$pkgs $cli_std"
		pkgs="$pkgs $cros_crostini"
		;;
	*)
		echo "unknown device: $host"
		exit 1
		;;
esac

qeq="$(pacman -Qeq)"
if [ -n "$qeq" ]; then
	pacman -Dq --asdeps $qeq
fi

#pacman -S --needed $pkgs
pacman -Dq --asexplicit $pkgs
