#!/bin/sh

act=""
gov=""

if [ "$#" -gt 0 ]; then
	act="set"

	for arg in "$@"; do
		case "$arg" in
			set|get|cpu|gpu)
				act="$arg"
				;;
			*)
				gov="$arg"
				;;
		esac
	done
else
	act="get"
fi

cpufreq_gov=""
devfreq_gov=""
amdgpu_gov=""

case "$gov" in
	performance)
		cpufreq_gov="performance"
		devfreq_gov="performance"
		amdgpu_gov="high"
		;;
	powersave)
		cpufreq_gov="powersave"
		devfreq_gov="powersave"
		amdgpu_gov="low"
		;;
	ondemand|schedutil)
		cpufreq_gov="$gov"
		devfreq_gov="simple_ondemand"
		amdgpu_gov="auto"

		drv=$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_driver)
		if [ "$drv" = "intel_pstate" ]; then
			cpufreq_gov="powersave"
		fi
		;;
	*)
		act="get"
		gov=""
		;;
esac

cpufreq_set() {
	sysfs_cpufreq="/sys/devices/system/cpu/cpufreq"

	for sysfs_gov in $sysfs_cpufreq/policy*/scaling_governor; do
		if [ "$act" = "set" -o "$act" = "cpu" ]; then
			echo "$cpufreq_gov" > "$sysfs_gov"
		fi

		echo "$sysfs_gov: $(cat $sysfs_gov)"
	done
}

devfreq_set() {
	if [ "$devfreq_gov" = "performance" ]; then
		suspend_delay="-1"
	else
		suspend_delay="66"
	fi

	sysfs_devfreq="/sys/class/devfreq"

	for sysfs_gpu in $sysfs_devfreq/*.gpu; do
		[ -d "$sysfs_gpu" ] || continue

		sysfs_gov="$sysfs_gpu/governor"
		sysfs_sus="$sysfs_gpu/device/power/autosuspend_delay_ms"

		if [ "$act" = "set" -o "$act" = "gpu" ]; then
			echo "$devfreq_gov" > "$sysfs_gov"
			echo "$suspend_delay" > "$sysfs_sus"
		fi

		echo "$sysfs_gov: $(cat $sysfs_gov)"
		echo "$sysfs_sus: $(cat $sysfs_sus)"
	done
}

i915_set() {
	sysfs_drm="/sys/class/drm"

	for sysfs_card in $sysfs_drm/card*; do
		[ -d "$sysfs_card" ] || continue

		sysfs_min="$sysfs_card/gt_min_freq_mhz"
		[ -f "$sysfs_min" ] || continue

		sysfs_max="$sysfs_card/gt_max_freq_mhz"
		sysfs_rp0="$sysfs_card/gt_RP0_freq_mhz"
		sysfs_rpn="$sysfs_card/gt_RPn_freq_mhz"

		if [ "$act" = "set" -o "$act" = "gpu" ]; then
			case "$devfreq_gov" in
				performance)
					cp "$sysfs_rp0" "$sysfs_max"
					cp "$sysfs_rp0" "$sysfs_min"
					;;
				powersave)
					cp "$sysfs_rpn" "$sysfs_min"
					cp "$sysfs_rpn" "$sysfs_max"
					;;
				*)
					cp "$sysfs_rpn" "$sysfs_min"
					cp "$sysfs_rp0" "$sysfs_max"
					;;
			esac
		fi

		echo "$sysfs_min: $(cat $sysfs_min)"
		echo "$sysfs_max: $(cat $sysfs_max)"
	done
}

amdgpu_set() {
	sysfs_drm="/sys/class/drm"
	gov="$1"

	for sysfs_card in $sysfs_drm/card*; do
		[ -d "$sysfs_card" ] || continue

		sysfs_level="$sysfs_card/device/power_dpm_force_performance_level"
		[ -f "$sysfs_level" ] || continue

		if [ "$act" = "set" -o "$act" = "gpu" ]; then
			echo "$amdgpu_gov" > "$sysfs_level"
		fi

		echo "$sysfs_level: $(cat $sysfs_level)"
	done
}

cpufreq_set
devfreq_set
i915_set
amdgpu_set
