#!/bin/sh

cpu_governor="$1"
gpu_governor="$2"
suspend_delay="$3"

if [ -z "$gpu_governor" -a -n "$cpu_governor" ]; then
	case "$cpu_governor" in
	ondemand|schedutil)
		gpu_governor="simple_ondemand"
		;;
	userspace|powersave|performance|*)
		gpu_governor="$cpu_governor"
		;;
	esac
fi

if [ -n "$gpu_governor" ]; then
	if [ "$gpu_governor" = "performance" ]; then
		suspend_delay="-1"
	else
		suspend_delay="66"
	fi
fi

cpufreq_set_governor() {
	sysfs_cpufreq="/sys/devices/system/cpu/cpufreq"
	gov="$1"

	for sysfs_gov in $sysfs_cpufreq/policy*/scaling_governor; do
		if [ -n "$gov" ]; then
			echo "$gov" > "$sysfs_gov"
		fi

		echo "$sysfs_gov: $(cat $sysfs_gov)"
	done
}

devfreq_set_governor_and_pm() {
	sysfs_devfreq="/sys/class/devfreq"
	gov="$1"
	sus="$2"

	for sysfs_gpu in $sysfs_devfreq/*.gpu; do
		[ -d "$sysfs_gpu" ] || continue

		sysfs_gov="$sysfs_gpu/governor"
		sysfs_sus="$sysfs_gpu/device/power/autosuspend_delay_ms"

		if [ -n "$gov" ]; then
			echo "$gov" > "$sysfs_gov"
		fi

		echo "$sysfs_gov: $(cat $sysfs_gov)"

		if [ -n "$sus" ]; then
			echo "$sus" > "$sysfs_sus"
		fi

		echo "$sysfs_sus: $(cat $sysfs_sus)"
	done
}

i915_set_min_freq() {
	sysfs_drm="/sys/class/drm"
	gov="$1"

	for sysfs_card in $sysfs_drm/card*; do
		[ -d "$sysfs_card" ] || continue

		sysfs_min="$sysfs_card/gt_min_freq_mhz"
		[ -f "$sysfs_min" ] || continue

		sysfs_rp0="$sysfs_card/gt_RP0_freq_mhz"
		sysfs_rp1="$sysfs_card/gt_RP1_freq_mhz"

		if [ "$gov" = "performance" ]; then
			cp "$sysfs_rp0" "$sysfs_min"
		elif [ -n "$gov" ]; then
			cp "$sysfs_rp1" "$sysfs_min"
		fi

		echo "$sysfs_min: $(cat $sysfs_min)"
	done
}

cpufreq_set_governor "$cpu_governor"
devfreq_set_governor_and_pm "$gpu_governor" "$suspend_delay"
i915_set_min_freq "$gpu_governor"
