#!/bin/sh

CR="$HOME/chromium/src"
if [ ! -d "$CR" ]; then
	CR="$PWD"
fi

OPTS="--map-C++=+.mojom -ICOMPONENT_EXPORT+"

PROJECTS="base
	  cc
	  chrome/app
	  chrome/browser
	  chrome/common
	  components
	  content
	  gpu
	  media
	  sandbox
	  services
	  skia
	  third_party/khronos
	  third_party/libdrm
	  third_party/minigbm
	  third_party/skia
	  ui
	  "

CROS_PROJECTS=""
#CROS_PROJECTS="ash chromeos"

(cd "$CR" && ctags -R $OPTS $PROJECTS $CROS_PROJECTS)
