#!/bin/sh

if [ "$#" -ne 2 ]; then
	echo "$0 <out-dir> <dst-host>"
	exit 1
fi

out_dir="$1"
dst_host="$2"

if [ ! -d "$out_dir" ]; then
	echo "$out_dir is not a directory"
	exit 1
fi

dist_name="google-chrome-dist"

dist_exec="
	chrome
	chrome_crashpad_handler
	libvulkan.so.1
"
dist_exec="$dist_exec $(basename -a "$out_dir"/*.so)"

dist_data="
	chrome_100_percent.pak
	chrome_200_percent.pak
	icudtl.dat
	resources.pak
	v8_context_snapshot.bin
	vk_swiftshader_icd.json
"

dist_dirs="
	MEIPreload
	WidevineCdm
	locales
"

staging_dir="$out_dir/$dist_name"

echo "creating staging directory $staging_dir..."
mkdir -p "$staging_dir"

echo "stripping executables..."
for i in $dist_exec; do
	s="$out_dir/$i"
	d="$staging_dir/$i"
	[ "$s" -nt "$d" ] && strip -g -o "$d" "$s"
done

echo "symlinking data files..."
for i in $dist_data $dist_dirs; do
	ln -snf "../$i" "$staging_dir/$i"
done

#echo "creating tarball..."
#tar -chv --zstd -f "$dist_name.tar.zst" -C "$out_dir" "$dist_name"

echo "rsyncing to $dst_host..."
rsync -azP --copy-links "$staging_dir" "$dst_host:"
