#!/bin/sh

BOARD=""
HOST=""

PORT=1234
SYSROOT="/build/$BOARD"

PROJECTS="src/platform/drm-tests
	  src/platform/minigbm
	  src/third_party/libdrm
	  src/third_party/mesa
	  src/third_party/virglrenderer"
SRC_DIRS="."
for project in $PROJECTS; do
	SRC_DIRS="$SRC_DIRS:$HOME/trunk/$project"
done

$HOST-gdb \
        -ex "set sysroot $SYSROOT" \
        -ex "set solib-absolute-prefix $SYSROOT" \
        -ex "set debug-file-directory $SYSROOT/usr/lib/debug" \
        -ex "set directories $SRC_DIRS" \
        -ex "target remote :$PORT" \
	$@
