#!/bin/sh

# for rescue (~300M)
cli_min="
	btrfs-progs
	dosfstools
	e2fsprogs
	fdisk
	init
	udev
	vim
"

# for all devices including servers (~100M)
cli_base="
	$cli_min
	curl
	htop
	iproute2
	iputils-ping
	ldnsutils
	less
	logrotate
	openssh-client
	openssh-server
	pciutils
	procps
	rsync
	smartmontools
	sudo
	systemd-resolved
	usbutils
	whiptail
"

# for workstations, vms, and duts (~200M)
cli_std="
	$cli_base
	bc
	file
	git
	locales
	lsof
	man-db
	manpages
	ncal
	python3
	python3-venv
	strace
	tmux
	unzip
	zip
"

# for workstations (~50M)
cli_full="
	$cli_std
	gnupg
	jq
	picocom
	systemd-container
	wireguard-tools
"

# for terminal (~400M)
gui_min="
	alacritty
	fonts-noto-core
	i3status
	polkitd
	sway
"

# for basic use (~250M)
gui_base="
	$gui_min
	brightnessctl
	grim
	mesa-utils
	slurp
	swayidle
	swayimg
	swaylock
	vulkan-tools
	wayland-utils
	wl-clipboard
"

# for real use (~1100M)
gui_std="
	$gui_base
	fcitx5
	fcitx5-chewing
	fonts-noto-cjk
	fonts-noto-color-emoji
	google-chrome-stable
	mako-notifier
	pipewire-pulse
"

# for optional features (~500M)
gui_full="
	$gui_std
	cups
	mpv
	xdg-desktop-portal-gtk
	xdg-desktop-portal-wlr
"

# for tooling (~100M)
dev_min="
	gdb
	linux-perf
	make
	manpages-dev
	trace-cmd
	universal-ctags
"

# for development (~700M)
dev_base="
	$dev_min
	build-essential
	ccache
	clang-format
	cmake
	meson
	pkgconf
"

# for cross-compile (~800M)
dev_cross="
	debootstrap
	gcc-aarch64-linux-gnu
	g++-aarch64-linux-gnu
	qemu-user
	qemu-user-binfmt
"

# for kernel (~100M)
# all except libelf-dev are for cros kernel
dev_kernel="
	device-tree-compiler
	libelf-dev
	lz4
	vboot-kernel-utils
"

# for mesa (~1000M)
dev_mesa="
	bison
	flex
	glslang-tools
	libclang-cpp-dev
	libclang-dev
	libclc-21-dev
	libdrm-dev
	libllvmspirvlib-21-dev
	libwayland-dev
	libx11-xcb-dev
	libxcb1-dev
	libxcb-dri3-dev
	libxcb-present-dev
	libxcb-randr0-dev
	libxcb-shm0-dev
	libxrandr-dev
	libxshmfence-dev
	llvm-dev
	spirv-tools-dev
"

kernel_min="
	systemd-zram-generator
"

kernel_x86="
	$kernel_min
	linux-image-amd64
"

kernel_arm="
	$kernel_min
	linux-image-arm64
"

kernel_uki="
	systemd-ukify
"

soc_intel="
	firmware-intel-graphics
	intel-microcode
	mesa-vulkan-drivers
"

soc_mtk="
	firmware-mediatek
"

net_intel="
	firmware-iwlwifi
"

net_rt="
	firmware-realtek
"

net_wifi="
	iw
	wireless-regdb
	wpasupplicant
"

misc_x86="
	linux-cpupower
"

mach_rpi="
	cnrdrvcups-ufr2-us
	git
	hdparm
	ksmbd-tools
	msmtp
	nginx
	php-fpm
	python3
	python3-venv
	podman
	systemd-journal-remote
	tmux
	zip
"

mach_npi="
	firmware-realtek
	kea-dhcp4-server
	nftables
	systemd-journal-remote
	unbound
"

mach_crostini="
	cros-garcon
	cros-port-listener
	cros-sommelier
	cros-sommelier-config
	cros-wayland
	gnupg
"

pkgs=""

host="$(uname -n)"
case "$host" in
	"rpi")
		pkgs="$pkgs $cli_base $kernel_arm $mach_rpi"
		;;
	"npi")
		pkgs="$pkgs $cli_base $kernel_arm $mach_npi"
		;;
	"penguin")
		pkgs="$pkgs $cli_std $dev_min $mach_crostini"
		;;
	*)
		echo "unknown device: $host"
		exit 1
		;;
esac

manual="$(apt-mark showmanual)"
if [ -n "$manual" ]; then
	apt-mark auto $manual > /dev/null
fi

#apt install $pkgs
apt-mark manual $pkgs | grep -v ' set to manually installed\.$'
