#!/bin/sh

set -e

src_dir="$PWD"
if [ ! -d "$src_dir/external/vulkancts" ]; then
	echo "this script must be run from the top directory of VK-GL-CTS"
	exit 1
fi

if [ "$#" -ne 3 ]; then
	echo "usage: $0 <out-dir> <version> <x86_64|aarch64>"
	exit 1
fi
out_dir=$(realpath "$1")
version="$2"
arch="$3"

dist_name="deqp-$version-$arch"

dist_out_exec="
	executor/testlog-to-xml
	external/vulkancts/modules/vulkan/deqp-vk
	external/openglcts/modules/glcts
	modules/egl/deqp-egl
	modules/gles2/deqp-gles2
	modules/gles3/deqp-gles3
	modules/gles31/deqp-gles31
"

dist_out_data="
	external/vulkancts/modules/vulkan/vulkan
	external/openglcts/modules/gl_cts
	modules/gles2/gles2
	modules/gles3/gles3
	modules/gles31/gles31
"

dist_src_data="
	android/cts/main
	doc/testlog-stylesheet
	external/vulkancts/mustpass/main/vk-default.txt
	external/vulkancts/mustpass/main/vk-default
"

echo "creating staging directory $dist_name..."
mkdir "$dist_name"

for i in $dist_out_exec $dist_out_data; do
	ln -snf "$out_dir/$i" "$dist_name"
done

for i in $dist_src_data; do
	ln -snf "$src_dir/$i" "$dist_name"
done

echo "stripping executables..."
(cd "$out_dir" && $arch-linux-gnu-strip -g $dist_out_exec)

echo "creating tarball..."
tar -chf "$dist_name.tar" "$dist_name"
rm -rf "$dist_name"

echo "creating $dist_name.tar.zst..."
zstd "$dist_name.tar"
echo "creating $dist_name.tar.gz..."
gzip "$dist_name.tar"
