#!/bin/sh

kernel_makefiles=""
if [ $# -ge 1 ]; then
	kernel_src="$1"
	kernel_makefiles=$(find "$kernel_src" -name Makefile)
fi

find_config() {
	module="$1"

	# obj-$(CONFIG_FOO) += foo.o
	regex="^obj-\$(CONFIG_.*= $module\.o$"
	grep -h "$regex" $kernel_makefiles | cut -d'(' -f2 | cut -d')' -f1
}

sysfs_devices=$(find /sys/devices -name modalias -exec dirname {} \; | sort)
for dev in $sysfs_devices; do
	modalias=$(cat "$dev/modalias")

	driver=""
	if [ -h "$dev/driver" ]; then
		driver=" $(basename $(realpath "$dev/driver"))"
	fi

	modules=""
	if [ -n "$modalias" ]; then
		modules=$(modprobe -R -q "$modalias" | tr '\n' ' ')

		modalias=" $modalias"
		if [ -n "$modules" ]; then
			modules=" ${modules% }"
		fi
	fi

	configs=""
	if [ -n "$kernel_makefiles" ]; then
		for m in $modules; do
			config=$(find_config "$m")

			# try again
			if [ -z "$config" ]; then
				m=$(echo "$m" | tr _ -)
				config=$(find_config "$m")
			fi

			if [ -n "$config" ]; then
				configs="$configs $config"
			fi
		done
	fi

	echo "$dev"
	echo "  modalias:$modalias"
	echo "  driver:$driver"
	echo "  modules:$modules"
	echo "  configs:$configs"
done
