#!/bin/sh

case "$#" in
	0)
		action="do_dump"
		;;
	2)
		action="do_parse"
		;;
	*)
		echo "Usage: $0 [<dump-file> <kernel-tree>]"
		exit 1
esac

do_dump() {
	while read -rd '' dev; do
		subsystem=""
		if [ -h "$dev/subsystem" ]; then
			subsystem=$(realpath "$dev/subsystem")
		fi

		modalias=""
		if [ -f "$dev/modalias" ]; then
			modalias=$(cat "$dev/modalias")
		fi

		driver=""
		if [ -h "$dev/driver" ]; then
			driver=$(realpath "$dev/driver")
		fi

		firmware_node=""
		if [ -h "$dev/firmware_node" ]; then
			firmware_node=$(realpath "$dev/firmware_node")
		fi

		name=""
		if [ -f "$dev/name" ]; then
			name=$(cat "$dev/name")
		fi

		modules=""
		if [ -n "$modalias" ]; then
			modules=$(modprobe -R -q "$modalias" | sort | uniq | tr '\n' ' ')
			if [ -n "$modules" ]; then
				modules="${modules% }"
			fi
		fi

		echo "$dev"
		if [ -n "$subsystem" ]; then
			echo "  subsystem: $subsystem"
		fi
		if [ -n "$modalias" ]; then
			echo "  modalias: $modalias"
		fi
		if [ -n "$driver" ]; then
			echo "  driver: $driver"
		fi
		if [ -n "$firmware_node" ]; then
			echo "  firmware_node: $firmware_node"
		fi
		if [ -n "$name" ]; then
			echo "  name: $name"
		fi
		if [ -n "$modules" ]; then
			echo "  modules: $modules"
		fi
	done < <(find "/sys/devices" -name "uevent" -print0 | xargs -0 dirname -z | sort -z)
}

do_parse() {
	dump_file="$1"
	kernel_tree="$2"

	kernel_makefiles=$(find "$kernel_tree" -name Makefile)

	while read line; do
		modules=""
		case "$line" in
			/sys/devices/*)
				echo "$line"
				;;
			modules:*)
				echo "  $line"
				modules="${line#modules: }"
				;;
			*)
				echo "  $line"
				;;
		esac

		configs=""
		if [ -n "$modules" ]; then
			for mod in $modules; do
				# obj-$(CONFIG_FOO) += foo.o
				regex=$(echo "$mod" | tr _ .)
				regex="^obj-\$(CONFIG_.*= $regex\.o$"

				conf=$(grep -h "$regex" $kernel_makefiles | cut -d'(' -f2 | cut -d')' -f1)
				if [ -n "$conf" ]; then
					configs="$configs $conf"
				fi
			done

			if [ -n "$configs" ]; then
				configs="${configs# }"
			fi
		fi

		if [ -n "$configs" ]; then
			echo "  configs: $configs"
		fi
	done < "$dump_file"
}

"$action" "$@"
