#!/bin/sh

act=""
gov=""

if [ "$#" -gt 0 ]; then
	act="set"

	for arg in "$@"; do
		case "$arg" in
			set|get|cpu|gpu)
				act="$arg"
				;;
			*)
				gov="$arg"
				;;
		esac
	done
else
	act="get"
fi

cpufreq_gov=""
rpm_gov=""
devfreq_gov=""
amdgpu_gov=""

case "$gov" in
	performance)
		cpufreq_gov="performance"
		rpm_gov="on"
		devfreq_gov="performance"
		amdgpu_gov="profile_peak"
		;;
	powersave)
		cpufreq_gov="powersave"
		rpm_gov="auto"
		devfreq_gov="powersave"
		amdgpu_gov="low"
		;;
	ondemand|schedutil)
		cpufreq_gov="$gov"
		rpm_gov="auto"
		devfreq_gov="simple_ondemand"
		amdgpu_gov="auto"

		drv=$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_driver)
		if [ "$drv" = "intel_pstate" -o "$drv" = "amd-pstate-epp" ]; then
			cpufreq_gov="powersave"
		fi
		;;
	*)
		act="get"
		gov=""
		;;
esac

cpufreq_set() {
	sysfs_cpufreq="/sys/devices/system/cpu/cpufreq"

	for sysfs_pol in $sysfs_cpufreq/policy*; do
		[ -d "$sysfs_pol" ] || continue

		sysfs_gov="$sysfs_pol/scaling_governor"

		if [ "$act" = "set" -o "$act" = "cpu" ]; then
			echo "$cpufreq_gov" > "$sysfs_gov"
		fi

		echo "$sysfs_gov: $(cat $sysfs_gov)"
	done
}

rpm_set() {
	sysfs_dev="$1"
	sysfs_gov="$1/power/control"

	if [ "$act" = "set" -o "$act" = "gpu" ]; then
		echo "$rpm_gov" > "$sysfs_gov"
	fi

	echo "$sysfs_gov: $(cat $sysfs_gov)"
}

devfreq_set() {
	sysfs_devfreq="/sys/class/devfreq"

	for sysfs_gpu in $sysfs_devfreq/*.gpu; do
		[ -d "$sysfs_gpu" ] || continue

		rpm_set "$sysfs_gpu"

		sysfs_gov="$sysfs_gpu/governor"

		if [ "$act" = "set" -o "$act" = "gpu" ]; then
			echo "$devfreq_gov" > "$sysfs_gov"
		fi

		echo "$sysfs_gov: $(cat $sysfs_gov)"
	done
}

xe_set() {
	sysfs_drm="/sys/class/drm"

	for sysfs_card in $sysfs_drm/card*; do
		[ -d "$sysfs_card" ] || continue

		sysfs_min="$sysfs_card/device/tile0/gt0/freq0/min_freq"
		[ -f "$sysfs_min" ] || continue

		sysfs_max="$sysfs_card/device/tile0/gt0/freq0/max_freq"
		sysfs_rp0="$sysfs_card/device/tile0/gt0/freq0/rp0_freq"
		sysfs_rpe="$sysfs_card/device/tile0/gt0/freq0/rpe_freq"

		if [ "$act" = "set" -o "$act" = "gpu" ]; then
			case "$devfreq_gov" in
				performance)
					cp "$sysfs_rp0" "$sysfs_max"
					cp "$sysfs_rp0" "$sysfs_min"
					;;
				powersave)
					cp "$sysfs_rpe" "$sysfs_min"
					cp "$sysfs_rpe" "$sysfs_max"
					;;
				*)
					cp "$sysfs_rpe" "$sysfs_min"
					cp "$sysfs_rp0" "$sysfs_max"
					;;
			esac
		fi

		echo "$sysfs_min: $(cat $sysfs_min)"
		echo "$sysfs_max: $(cat $sysfs_max)"
	done
}

i915_set() {
	sysfs_drm="/sys/class/drm"

	for sysfs_card in $sysfs_drm/card*; do
		[ -d "$sysfs_card" ] || continue

		sysfs_min="$sysfs_card/gt_min_freq_mhz"
		[ -f "$sysfs_min" ] || continue

		sysfs_max="$sysfs_card/gt_max_freq_mhz"
		sysfs_rp0="$sysfs_card/gt_RP0_freq_mhz"
		sysfs_rpn="$sysfs_card/gt_RPn_freq_mhz"

		if [ "$act" = "set" -o "$act" = "gpu" ]; then
			case "$devfreq_gov" in
				performance)
					cp "$sysfs_rp0" "$sysfs_max"
					cp "$sysfs_rp0" "$sysfs_min"
					;;
				powersave)
					cp "$sysfs_rpn" "$sysfs_min"
					cp "$sysfs_rpn" "$sysfs_max"
					;;
				*)
					cp "$sysfs_rpn" "$sysfs_min"
					cp "$sysfs_rp0" "$sysfs_max"
					;;
			esac
		fi

		echo "$sysfs_min: $(cat $sysfs_min)"
		echo "$sysfs_max: $(cat $sysfs_max)"
	done
}

amdgpu_set() {
	sysfs_drm="/sys/class/drm"
	gov="$1"

	for sysfs_card in $sysfs_drm/card*; do
		[ -d "$sysfs_card" ] || continue

		sysfs_level="$sysfs_card/device/power_dpm_force_performance_level"
		[ -f "$sysfs_level" ] || continue

		if [ "$act" = "set" -o "$act" = "gpu" ]; then
			echo "$amdgpu_gov" > "$sysfs_level"
		fi

		echo "$sysfs_level: $(cat $sysfs_level)"
	done
}

cpufreq_set
devfreq_set
xe_set
i915_set
amdgpu_set
