#!/usr/bin/env python

import argparse
import json

from bs4 import BeautifulSoup


def parse_gizmo_config(config_str):
    config = json.loads(config_str)

    urls = config['downloadUrls']
    assert len(urls) == 1
    url = urls[0]['url']

    print(url)


def parse_html(fp):
    soup = BeautifulSoup(fp, 'html.parser')
    buttons = soup.select(
        'div.item-bar:not(.list-dropdown) button.library-action.export-file'
    )
    for button in buttons:
        config = button['data-kobo-gizmo-config']
        parse_gizmo_config(config)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Parse Kobo books.html for URLLink.acsm URLs'
    )
    parser.add_argument('filename', help='path to <books.html>')
    return parser.parse_args()


def main():
    args = parse_args()
    with open(args.filename) as fp:
        parse_html(fp)


if __name__ == '__main__':
    main()
