#!/bin/sh

# Tips for arc
#
#  - the toolchain tarball url can be found at
#    https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/refs/heads/main/sys-devel/arc-toolchain-r
#
# Tips for ndk
#
#  - specify both sysroot and ndk_root if pkg-config is used

ndk_api="28"

if [ $# -lt 4 ]; then
	echo "$0 <linux|cros|arc-p|arc-r|arc-t|ndk> <x86|arm> <64|32> <sysroot> [arc_root|ndk_root]"
	exit 1
fi

flavor="$1"
arch="$2"
bits="$3"
sysroot="$4"
toolchain_root="$5"

init_vars() {
	# https://mesonbuild.com/Reference-tables.html#cpu-families
	# https://wiki.debian.org/Multiarch/Tuples
	# https://clang.llvm.org/docs/CrossCompilation.html
	meson_system=""
	meson_cpu_family=""
	meson_cpu=""
	local target_arch=""
	local target_vendor=""
	local target_sys="linux"
	local target_env=""

	case "$arch-$bits" in
		x86-64)
			meson_cpu_family="x86_64"
			meson_cpu="x86_64"
			target_arch="x86_64"
			;;
		x86-32)
			meson_cpu_family="x86"
			meson_cpu="i686"
			target_arch="i386"
			;;
		arm-64)
			meson_cpu_family="aarch64"
			meson_cpu="aarch64"
			target_arch="aarch64"
			;;
		arm-32)
			meson_cpu_family="arm"
			meson_cpu="armv7a"
			target_arch="arm"
			target_env="eabihf"
			;;
		*)
			echo "unknown $arch-$bits"
			exit 1
			;;
	esac
	case "$flavor" in
		linux)
			meson_system="linux"
			target_env="gnu$target_env"
			;;
		cros)
			meson_system="linux"
			target_arch="$meson_cpu"
			target_vendor="cros-"
			target_env="gnu$target_env"
			;;
		arc-p|arc-r|arc-t)
			meson_system="android"
			target_arch="$meson_cpu"
			target_env="android${target_env%hf}"
			;;
		ndk)
			meson_system="android"
			target_arch="$meson_cpu"
			target_env="android${target_env%hf}$ndk_api"
			;;
		*)
			echo "unknown $flavor"
			exit 1
			;;
	esac

	local target_triple="$target_arch-$target_vendor$target_sys-$target_env"
	llvm_config=""
	c_link_args=""
	cpp_args=""
	cpp_link_args=""

	case "$flavor" in
		linux)
			toolchain_prefix=""
			if [ "$arch" != "x86" ]; then
				toolchain_prefix="$target_triple-"
			fi

			common_args="'--sysroot', sysroot"
			if [ "$arch-$bits" = "x86-32" ]; then
				common_args="'-m32', $common_args"
			fi
			;;
		cros)
			toolchain_prefix=""
			common_args="'-target', '$target_triple', '--sysroot', sysroot"
			llvm_config="/usr/lib/llvm/bin/llvm-config-host"
			;;
		arc-*)
			if [ -z "$toolchain_root" ]; then
				toolchain_root="$sysroot"
				sysroot="/not-exist"
			fi

			local arc_llvm_ver=""
			local arc_gcc_ver="4.9"
			local arc_gcc_arch=""
			local arc_gcc_env=""
			local arc_sysroot_arch=""
			case "$flavor" in
				arc-p)
					arc_llvm_ver="6.0"
					;;
				arc-r)
					arc_llvm_ver="11.0.2"
					;;
				arc-t)
					arc_llvm_ver="14.0.5"
					;;
			esac
			case "$arch-$bits" in
				x86-*)
					arc_gcc_arch="x86_64"
					arc_gcc_env="android"
					arc_sysroot_arch="amd64"
					;;
				arm-64)
					arc_gcc_arch="aarch64"
					arc_gcc_env="android"
					arc_sysroot_arch="arm64"
					;;
				arm-32)
					arc_gcc_arch="arm"
					arc_gcc_env="androideabi"
					arc_sysroot_arch="arm64"
					;;
			esac

			toolchain_prefix="$toolchain_root/arc-llvm/$arc_llvm_ver/bin/"
			llvm_config="/opt/google/containers/android/build/bin/llvm-config-host"

			local arc_gcc="$toolchain_root/arc-gcc/$arc_gcc_arch/$arc_gcc_arch-linux-$arc_gcc_env-$arc_gcc_ver"
			local arc_sysroot="$toolchain_root/$arc_sysroot_arch"
			common_args="'-target', '$target_triple', '--sysroot', '$arc_sysroot', '-isystem', sysroot + '/usr/include'"
			c_link_args="'-Wl,--allow-shlib-undefined'"
			cpp_link_args="'-Wl,--allow-shlib-undefined'"
			case "$flavor" in
				arc-p)
					common_args="$common_args, '-gcc-toolchain', '$arc_gcc'"
					cpp_args="'-stdlib=libc++'"
					cpp_link_args="$cpp_link_args, '-stdlib=libc++'"
					;;
				arc-r)
					common_args="$common_args, '-gcc-toolchain', '$arc_gcc'"
					cpp_args="'-nostdinc++', '-I$arc_sysroot/usr/include/c++/$arc_gcc_ver'"
					c_link_args="$c_link_args, '-fuse-ld=lld'"
					cpp_link_args="$cpp_link_args, '-fuse-ld=lld'"
					;;
				arc-t)
					cpp_args="'-nostdinc++', '-I$arc_sysroot/usr/include/c++/$arc_gcc_ver'"
					c_link_args="$c_link_args, '-fuse-ld=lld'"
					cpp_link_args="$cpp_link_args, '-fuse-ld=lld'"
					;;
			esac
			;;
		ndk)
			if [ -z "$toolchain_root" ]; then
				toolchain_root="$sysroot"
				sysroot="/not-exist"
			fi

			toolchain_prefix="$toolchain_root/toolchains/llvm/prebuilt/linux-x86_64/bin/"
			common_args="'-target', '$target_triple', '-isystem', sysroot + '/usr/include'"
			cpp_link_args="'-static-libstdc++'"
			;;
	esac

	local basedirs="/usr/lib /usr/lib64 /usr/lib/$target_triple /usr/share"
	pkgconfigdirs=""
	for b in $basedirs; do
		if [ -d "$sysroot$b/pkgconfig" ]; then
			pkgconfigdirs="$pkgconfigdirs:$sysroot$b/pkgconfig"
		fi
	done
	pkgconfigdirs="${pkgconfigdirs#:}"
}

init_vars

gen_constants() {
	cat <<EOF
[constants]
toolchain_prefix = '$toolchain_prefix'
sysroot = '$sysroot'
common_args = [$common_args]
EOF
}

gen_binaries_gcc() {
	cat <<EOF
[binaries]
ar = toolchain_prefix + 'ar'
c = ['ccache', toolchain_prefix + 'gcc']
cpp = ['ccache', toolchain_prefix + 'g++']
strip = toolchain_prefix + 'strip'
pkgconfig = '/usr/bin/pkg-config'
EOF
}

gen_binaries_llvm() {
	cat <<EOF
[binaries]
ar = toolchain_prefix + 'llvm-ar'
c = ['ccache', toolchain_prefix + 'clang']
cpp = ['ccache', toolchain_prefix + 'clang++']
strip = toolchain_prefix + 'llvm-strip'
pkgconfig = '/usr/bin/pkg-config'
llvm-config = sysroot + '$llvm_config'
EOF
}

gen_builtin_options() {
	cat <<EOF
[built-in options]
c_args = common_args + []
c_link_args = common_args + [$c_link_args]
cpp_args = common_args + [$cpp_args]
cpp_link_args = common_args + [$cpp_link_args]
EOF
}

gen_properties() {
	# only for PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_LIBDIR
	cat <<EOF
[properties]
sys_root = sysroot
pkg_config_libdir = '$pkgconfigdirs'
EOF
}

gen_host_machine() {
	cat <<EOF
[host_machine]
system = '$meson_system'
cpu_family = '$meson_cpu_family'
cpu = '$meson_cpu'
endian = 'little'
EOF
}

gen_constants
echo
case "$flavor" in
	linux)
		gen_binaries_gcc
		;;
	cros|arc-*|ndk)
		gen_binaries_llvm
		;;
esac
echo
gen_builtin_options
echo
gen_properties
echo
gen_host_machine
