#!/bin/sh

GENERAL_OPTS="
	-name my-vm,debug-threads=on
	-mon my-serial
"

MACHINE_OPTS="
	-machine q35,pflash0=my-efi,pflash1=my-efivars,i8042=off
	-cpu host
	-accel kvm
	-smp 2
	-m 2G
	-nodefaults
"

EFI_OPTS="
	-blockdev driver=file,node-name=my-efi,read-only=on,filename=OVMF_CODE.secboot.4m.fd
	-blockdev driver=file,node-name=my-efivars,filename=OVMF_VARS.4m.fd
"

UI_OPTS="
	-device virtio-vga-gl
	-device virtio-keyboard
	-device virtio-mouse
	-display sdl,gl=on
"

SERIAL_OPTS="
	-device virtio-serial
	-device virtconsole,chardev=my-serial
	-chardev stdio,id=my-serial,signal=off,mux=on
"

# also ttyS0
#SERIAL_OPTS="$SERIAL_OPTS -device pci-serial,chardev=my-serial"

NETWORK_OPTS="
	-device virtio-net,netdev=my-net
	-netdev user,id=my-net,hostfwd=tcp::2222-:22
"

BLOCK_OPTS="
	-device virtio-blk,drive=my-drive
	-blockdev driver=file,node-name=my-image,filename=test.img
	-blockdev driver=raw,node-name=my-drive,file=my-image
"

export SDL_VIDEO_ALLOW_SCREENSAVER=1

#gdb --args \
qemu-system-x86_64 \
	$GENERAL_OPTS \
	$MACHINE_OPTS \
	$EFI_OPTS \
	$UI_OPTS \
	$SERIAL_OPTS \
	$NETWORK_OPTS \
	$BLOCK_OPTS \
	"$@"
